name: Test JXA script

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test JXA script
      run: osascript test.js
